ionos-cloud/terraform-provider-ionoscloud

- README.md
Hi,
this is a minor change, the link to the provider docs in the README.md was leading to a 404. The link has been updated to point to the latest version of docs on TF registry.
Cheers,
Janosch
> Updated link to IonosCloud Provider docs in README

- ionoscloud/resource_volume.go
fix: fixes #29 - correcter parameter in volume error message with licence_type instead of licenceType
> fix: fixes #29 - corrected parameter name in volume error message

- ionoscloud/resource_lan.go
fix: fixes #40 - ip_failover just computed for lan resource
> fix: fixes #40 - ip_failover just computed for lan resource

- CHANGELOG.md
- docs/data-sources/image.md
- docs/resources/volume.md
- ionoscloud/import_server_test.go
- ionoscloud/import_volume_test.go
- ionoscloud/resource_backup_unit.go
- ionoscloud/resource_datacenter.go
- ionoscloud/resource_firewall.go
- ionoscloud/resource_group.go
- ionoscloud/resource_ipblock.go
- ionoscloud/resource_ipfailover.go
- ionoscloud/resource_k8s_cluster.go
- ionoscloud/resource_k8s_node_pool.go
- ionoscloud/resource_lan.go
- ionoscloud/resource_loadbalancer.go
- ionoscloud/resource_nic.go
- ionoscloud/resource_private_crossconnect.go
- ionoscloud/resource_s3_key.go
- ionoscloud/resource_server.go
- ionoscloud/resource_server_test.go
- ionoscloud/resource_share.go
- ionoscloud/resource_snapshot.go
- ionoscloud/resource_user.go
- ionoscloud/resource_volume.go
- ionoscloud/resource_volume_test.go
- ionoscloud/utils.go
- Added userData and backupUnitId in the server volume 
- Added nil check for apiResponse.Response
- Fix issue #19 - fixed update ssh_key_path although not changed
- Fix issue  #93 - updated documentation with an usable example and removed image_aliases from the list of arguments used for search
> userData and backupUnitID in volume server + nil check on apiResponse.Response +  fixed issue #19

- CHANGELOG.md
- ionoscloud/resource_volume.go
- ionoscloud/resource_volume_test.go
- fixed #112 by sending in the attach request just the id of the volume
> fixed #112 - can't attach existing volume to server after recreating it

- ionoscloud/data_source_s3_key_test.go
- ionoscloud/resource_backup_unit.go
- ionoscloud/resource_backup_unit_test.go
- ionoscloud/resource_s3_key.go
- ionoscloud/resource_server.go
- ionoscloud/resource_user.go
- ionoscloud/resource_user_test.go
- ionoscloud/utils.go
Fix s3 key test, add some scenarios to test for user.
Fix: update user when only optional fields change.
> fix: allow user to be updated when only optional field changes

- ionoscloud/resource_k8s_node_pool.go
When migrating from an old state from provider version5, the state conversion fails causing a panic, since lans can be nil there. I put some small check around the interface conversion. Not sure if that's the ideal solution / how many additional checks should be done.
> fix conversion coming from a v5 state

- CHANGELOG.md
- go.mod
- main.go
Add v6 to go.mod to allow import of module.
> fix: Add versioning to go.mod

- CHANGELOG.md
- ionoscloud/resource_k8s_node_pool.go
Immutable node_pool fields should throw error on plan also, not only on apply.
Note: this will also throw an error on destroy, so if anyone wants to destroy the resource, they need to first restore the field to the original value and then run destroy.
> fix: immutable nopePool fields should throw error on plan

- CHANGELOG.md
- docs/data-sources/server.md
- ionoscloud/resource_server.go
primary_ip should not be set for server data source.
Primary_ip should be set when importing server resources.
> fix: primary_ip should be set only for resource

- CHANGELOG.md
- ionoscloud/resource_k8s_node_pool.go
Immutable node_pool fields should throw error on plan also, not only on apply.
Note: this will also throw an error on destroy, so if anyone wants to destroy the resource, they need to first restore the field to the original value and then run destroy.
> fix: v6 immutable nodepool fields should throw err on plan

- CHANGELOG.md
- docs/resources/k8s_cluster.md
- docs/resources/k8s_node_pool.md
- ionoscloud/data_source_k8s_cluster.go
- ionoscloud/data_source_k8s_cluster_test.go
- ionoscloud/data_source_k8s_node_pool.go
- ionoscloud/data_source_k8s_node_pool_test.go
- ionoscloud/import_k8s_cluster_test.go
- ionoscloud/import_loadbalancer_test.go
- ionoscloud/resource_k8s_cluster.go
- ionoscloud/resource_k8s_cluster_test.go
- ionoscloud/resource_k8s_node_pool.go
- ionoscloud/resource_k8s_node_pool_test.go
- ionoscloud/resource_loadbalancer_test.go
fixed diff on availableUpgradeVersions for k8s cluster and nodepool by removing this field from resource and import
> fix: fixed diff on availableUpgradeVersions for k8s cluster and nodepool

- CHANGELOG.md
- ionoscloud/provider.go
- ionoscloud/resource_k8s_node_pool.go
Increase timeout for nodepools.
> fix: increase nodepool timeout

- docs/resources/k8s_node_pool.md
Just tried to use the node pool verbatim from the docs, got:
```
Error: error creating k8s node pool: 422 Unprocessable Entity {
│   "httpStatus" : 422,
│   "messages" : [ {
│     "errorCode" : "200",
│     "message" : "[VDC-14-1830] Operation cannot be executed because the K8s version 1.18.5 is not viable for nodepools in cluster. Available versions are [1.20.10, 1.21.4, 1.21.9]"
│   } ]
│ }
```
So lets update the version
> doc: Update k8s node pool resource version

- docs/resources/k8s_cluster.md
Tried to use the resource verbatim, got this:
```
│ Error: error creating k8s cluster: 422 Unprocessable Entity {
│   "httpStatus" : 422,
│   "messages" : [ {
│     "errorCode" : "200",
│     "message" : "[VDC-14-1829] Operation cannot be executed because the K8s version 1.18.5 is not viable for cluster. Available versions are [1.20.10, 1.21.4, 1.21.9, 1.22.6]"
│   } ]
│ }
```
So lets update the version in the k8s docs
> doc: Update k8s cluster resource version

- CHANGELOG.md
- README.md
- docs/resources/k8s_node_pool.md
- ionoscloud/resource_k8s_node_pool.go
Adds optional field 'allow_replace'(default - false) to nodepool resource to allow the update of immutable fields by deleting and re-creating the resource.
fixes #218
> fix: allow_replace field to allow update of immutable fields

- CHANGELOG.md
- ionoscloud/resource_server.go
Remove deprecated image_name field from server resource.
> fix: remove image_name from volume for server

- CHANGELOG.md
- ionoscloud/resource_volume.go
- ionoscloud/resource_volume_test.go
Fixes crash on resource volume when using image_alias, without image_password and ssh_key_path.
Shows ssh_key_path or image_password error also for image_alias.
> fix: crash in volume resource when using image_alias with no image_password or ssh_key_path

- CHANGELOG.md
- ionoscloud/resource_k8s_node_pool.go
- ionoscloud/resource_k8s_node_pool_test.go
- introduced error when trying to set `max_node_count` equal to `min_node_count` in `k8s_node_pool`
- fixed crash when trying to disable `autoscaling` on `k8s_node_pool`
> fix: fixed crash when trying to disable autoscaling on k8s

- docs/resources/nic.md
- ionoscloud/resource_server.go
This pr will add the nic id to the server resource. 
I did not read the documentation properly and wasn't aware of the [primary_nic](https://registry.terraform.io/providers/ionos-cloud/ionoscloud/latest/docs/resources/server#primary_nic) computed value in this resource. 
My suggestion was to access the primary_nic id as follows: 
```hcl
resource "ionoscloud_server" "example" {
name              = "Server Example"
datacenter_id     = ionoscloud_datacenter.example.id
cores             = 1
ram               = 1024
availability_zone = "ZONE_1"
cpu_family        = "AMD_OPTERON"
image_name        = "Ubuntu-20.04"
image_password    = "123451231241"
volume {
name      = "system"
size      = 14
disk_type = "SSD"
}
nic {
name            = "default"
lan             = "1"
dhcp            = true …
```
> refactor: add id to primary nic in server_resource 

- ionoscloud/data_source_snapshot.go
You can now use snapshot data source size to reference when creating a server. Before it was not computed, so terraform did could not use it before the resource was created.
> fix: snapshot size, location and name should be computed in data source

- CHANGELOG.md
- docs/resources/k8s_node_pool.md
- ionoscloud/resource_k8s_cluster.go
`Maintenance_window` is now computed.
Updated documentation on how to configure lan when part of a nodepool. Add lifecycle `create_before_destroy` to make sure the order of deletion is first update nodepool and only after delete lan.
> fix: make maintenance window field computed

- CHANGELOG.md
- ionoscloud/resource_nic.go
Reproduced once: after a nic creation, the nic was not found in the api even though we wait until 'Available' state. 
Added a retry that will try for 5 minutes to find the nic and then use that nic to populate the fields.
> fix: retry for 5 minutes on nic not found after creation

- ionoscloud/resource_dbaas_mongo_user_test.go
- ionoscloud/resource_dbaas_mongodb_cluster.go
- ionoscloud/resource_dbaas_pgsql_cluster_test.go
de/txl mongo clusters remain busy forever. Using de/fra.
check list does not exist for psql.
> fix: mongo and psql tests

- docs/data-sources/dbaas_pgsql_backups.md
- ionoscloud/data_source_dbaas_pgsql_backups.go
- ionoscloud/resource_dbaas_pgsql_cluster_test.go
- services/dbaas/backups.go
Add `size` and `location` fields from v1.0.4 DBaaS PSQL release, but also other fields that were missing.
> feat: add new fields for PostgreSQL cluster backup data source

- ionoscloud/resource_server.go
When setting the `NIC` for a specific server, if no `primary_nic` is found, select the last `NIC` from the list of `NICs` instead of the first one.
> fix: change the way in which we set the NIC data

- ionoscloud/resource_k8s_node_pool_test.go
Fix nodepool test. Nodes could be either 1 or 2 after update. No sens in checking
> fix: nodepool test

- CHANGELOG.md
- ionoscloud/resource_dbaas_pgsql_cluster.go
- ionoscloud/resource_k8s_cluster.go
`viable_node_pool_versions` is no longer optional, only computed.
> fix: make viable_node_pool_versions only computed

- CHANGELOG.md
- docs/resources/server.md
- ionoscloud/import_server_test.go
- ionoscloud/resource_server.go
Server will allow passing primary nic and firewall rule for import so they are correctly populated.
> fix: allow server import with nic and firewall ids

- ionoscloud/data_source_dbaas_pgsql_backups.go
- ionoscloud/resource_dbaas_pgsql_cluster_test.go
Fix `TestAccDBaaSPgSqlClusterBasic` test failing because backups are crated later.
Wait 60 seconds before searching for backups.
> fix: sql backups data source not finding backups

- README.md
Remove DBaaS badge from readme.
> doc: remove dbaas badge from readme

- CHANGELOG.md
- docs/resources/k8s_node_pool.md
Update the k8s node pool documentation with a note related to the `node_count` usage. We did that because we had a discussion with a client and we thought that we can add a little bit of clarity to the documentation.
> doc: update doc for k8s node pool with a note

- .github/pull_request_template.md
- .github/workflows/compute-test-run.yml
- .github/workflows/dbaas-test-run.yml
- .github/workflows/k8s-test-run.yml
- .github/workflows/test.yml
Rename some test workflows considering that the tests are run weekly, not every 2 days as specified by the old name. Also, for some workflows, enforce the fetch in order to run the tests on the last commit in master. Previously, it was pretty annoying because for some pipelines the tests were failing because the tested code wasn't the latest.
> fix: fix workflows and rename some of them

- CHANGELOG.md
- docs/resources/k8s_cluster.md
- docs/resources/k8s_node_pool.md
- ionoscloud/resource_k8s_cluster.go
- ionoscloud/resource_k8s_node_pool.go
- ionoscloud/utils.go
Ignore downgrades of `k8s_version` patch level.
Allow upgrades of `k8s_version` patch level.
> fix: allow k8s_version patch upgrades, but ignore downgrades

- docs/resources/server.md
- docs/resources/snapshot.md
FIx examples using `ionoscloud_image` and use `image_alias` instead of `version` for lookup.
> doc: fix inonoscloud_image to use image_alias

- CHANGELOG.md
- ionoscloud/resource_server.go
Fix upgrade from 6.3.3 to higher versions for `ssh_keys` field. It was causing the server to be replaced.
> fix: ssh_keys upgrade from 6.3.3 to higher version

- CHANGELOG.md
- docs/data-sources/dbaas_mongo_cluster.md
- ionoscloud/data_source_dbaas_mongo_cluster.go
Remove the unpopulated `credentials` field from the MongoDB Cluster data source.
> remove credentials field

- ionoscloud/resource_server_test.go
cube servers allow only auto as av zone.
> fix: auto for cube servers

- CHANGELOG.md
- docs/resources/lan.md
- docs/resources/nic.md
- ionoscloud/data_source_nic_test.go
- ionoscloud/resource_lan_test.go
- ionoscloud/resource_nic.go
- ionoscloud/resource_nic_test.go
Allows user supplied values other than `AUTO` for the `ipv6_cidr_block` field of the nic resource.
> fix: allow custom value for ipv6_cidr_block

- CHANGELOG.md
- services/cloudapi/state.go
> fix: increase notfoundchecks to 9999 for k8s large clusters

- ionoscloud/data_source_image.go
- ionoscloud/resource_volume.go
fixes a bug in the `ionoscloud_image` data source where not all exact matches are included
> fix: image ds name exact matching

- .github/workflows/k8s-test-run.yml
I added `workflow_dispatch` on K8s workflow because I wanted to be able to run the tests manually, but the tests can be run using the `Test suite` action that is highly customizable.
> refactor: Remove 'workflow_dispatch' from K8s workflow

- CHANGELOG.md
- ionoscloud/data_source_k8s_cluster.go
- ionoscloud/data_source_k8s_clusters.go
- ionoscloud/resource_networkloadbalancer.go
Fixes an issue with the `server` field of K8s cluster data sources not being set
> Fix: Set server field for k8s cluster data sources

- .github/workflows/dbaas-test-run.yml
- CHANGELOG.md
Since we have more DBaaS services now it's cleaner if we have different run stages for each service.
The timeout values were selected as follows:
1. `MariaDB` - Only one cluster is created, by default cluster creation timeout is 60 minutes so the test, in the worst case, shouldn't take more than 70 minutes.
2. `MongoDB` and `PgSQL` - Before we had a 240 minute timeout for both pipelines, so for each I thought about 120 minute but I decided to increase the value a little bit to make sure that there is plenty of time.
> test: Modify DBaaS workflow to run tests in multiple stages

- CHANGELOG.md
- services/dataplatform/cluster.go
Fixes the first point presented here: https://github.com/ionos-cloud/terraform-provider-ionoscloud/issues/552.
Before this fix, if the `lans` wasn't present in the tf file, `lans: nil` would be send in the request, same for `routes`.
This led to a validation error since the API accepts `lans: null` only on `PATCH` requests, `routes: null` is not accepted at all.
The error looks like this:
```
│ Error: an error occured  while creating a Dataplatform Cluster: 422 Unprocessable Entity: {"httpStatus":422,"messages":[{"errorCode":"dsaas-400","message":"'Value is not nullable' caused by field /properties/lans"}]}
```
I modified the code and now, if the `lans` or `routes` are missing, instead of `nil` we send an empty list in the body request.
> fix: Fix 'lans' attribute for DataPlatform clusters

- CHANGELOG.md
- ionoscloud/resource_server.go
Adds an immutable field check for `template_uuid` to ensure the immutable field error is also raised when running `terraform plan`
> fix: check immutable field for template_uuid

- CHANGELOG.md
- ionoscloud/data_source_user.go
- ionoscloud/import_user_test.go
- ionoscloud/resource_user.go
- ionoscloud/resource_user_test.go
- fetch group ids using the depth of 1
- store group ids in state when fetching user resources
> fix: save user group ids in state when reading or importing

- ionoscloud/data_source_autoscaling_group.go
- ionoscloud/data_source_autoscaling_group_servers.go
- ionoscloud/data_source_autoscaling_group_servers_test.go
- ionoscloud/data_source_autoscaling_group_test.go
- ionoscloud/provider.go
- ionoscloud/resource_autoscaling_group.go
- ionoscloud/resource_autoscaling_group_test.go
The refactoring of ASG resources in their own package generates too much refactoring for now so i will leave them as the other resources in the ionoscloud big package.
> fix: move-back ASG files to ionoscloud package

- utils/utils.go
- utils/utils_test.go
Fixes a missed return and adds an ID to fix this test
```
=== RUN   TestWaitForResourceToBeReady
=== RUN   TestWaitForResourceToBeReady/TestReturnTrue
2024/07/11 12:03:12 [DEBUG] Waiting for state to become: [success]
=== RUN   TestWaitForResourceToBeReady/TestTimeoutOnReturnFalse
2024/07/11 12:03:12 [DEBUG] Waiting for state to become: [success]
2024/07/11 12:03:12 [DEBUG] resource with id test not ready, still trying 
2024/07/11 12:03:12 [TRACE] Waiting 500ms before next try
2024/07/11 12:03:13 [DEBUG] resource with id test not ready, still trying 
2024/07/11 12:03:13 [TRACE] Waiting 1s before next try
--- PASS: TestWaitForResourceToBeReady (1.00s)
--- PASS: TestWaitForResourceToBeReady/TestReturnTrue (0.00s)
--- PASS: TestWaitForResourceToBeReady/TestTimeoutOnReturnFalse (1.00s)
PASS …
```
> fix: failing WaitForResourceToBeReady test

- ionoscloud/import_apigateway_test.go
- ionoscloud/resource_apigateway_test.go
Adds Gateway tests
note: don't merge this until the API works seamlessly with the prod JWTs, currently it requires staging tokens which reset periodically and it would be a pain to manage separately.
> test: add gateway resource tests

- docs/resources/dbaas_mongo_cluster.md
This is just correcting the URL reference to API docs that have been restructured.
> doc: fix URL to docs page about network preparation

- CHANGELOG.md
- docs/resources/dbaas_mariadb_cluster.md
- ionoscloud/data_source_dbaas_mariadb_backups.go
- ionoscloud/data_source_dbaas_mariadb_cluster.go
- ionoscloud/resource_dbaas_mariadb_cluster.go
- ionoscloud/resource_dbaas_mariadb_cluster_test.go
- utils/constant/constants.go
Fix MariaDB tests by updating the image name for the server used in the tests.
Change the name of the `locations` constant. In the beginning I named this `MariaDBClusterLocations` or something like that but the slice can be used for multiple services. We will use this slice for all the services where multiple locations are supported. If a service supports less locations, we will create a special constant for that particular service.
> test: Fix MariaDB tests and change the name of 'locations' constant

- CHANGELOG.md
- ionoscloud/data_source_backup_unit.go
- ionoscloud/resource_backup_unit.go
- ionoscloud/resource_backup_unit_test.go
Fixes https://github.com/ionos-cloud/terraform-provider-ionoscloud/issues/641
There is a problem with the BackupUnits API:
- `GET` on all the BackupUnits works properly;
- `GET` on `BackupUnits/BackupUnitID` doesn't work properly (the state in the response is `BUSY` and some fields are not populated properly)
Because of that, the client method `BackupunitsFindById` doesn't work properly.
I will open a bug for the API team, but until then I implemented a workaround: I created a method that simulates the `BackupunitsFindById` client method. The difference is that this method fetches all the backup units and then returns the searched one using ID matching.
> fix: Implement workaround for the BackupUnits API bug

- docs/index.md
This PR fixes the documentation index page by moving the example manifest for resource timeouts to the correct section. The content of the debugging section remains unchanged, but its placement has been adjusted to follow the resource timeout section.
Also, removing an invalid code block start that renders following sections wrong.
> fix: move example code for resource timeouts to correct section

- CHANGELOG.md
- services/containerregistry/registries.go
- utils/constant/constants.go
Fix update behavior for `apiSubnetAllowList` property.
> fix: Fix update behavior for CR property

- CHANGELOG.md
- docs/data-sources/certificate_manager_certificate.md
- ionoscloud/data_source_certificate_manager_certificate.go
From the code, it looks like we want to be able to get a certificate using both `ID` and `name`. The functionality was not correct and I fixed it. However, I am not sure why would we want to get a certificate using both `ID` and `name`, one of them should be enough, just like we do for the other resources. I kept the functionality but maybe we need to change it (`ID` or `name`, not both, but it will be a breaking change).
> fix: Fix 'ionoscloud_certificate' data source

- CHANGELOG.md
- docs/resources/dbaas_mongo_cluster.md
- ionoscloud/resource_dbaas_mariadb_cluster_test.go
- ionoscloud/resource_dbaas_mongodb_cluster_test.go
- ionoscloud/resource_dbaas_pgsql_cluster.go
- ionoscloud/resource_dbaas_pgsql_user_test.go
> test: Fix DBaaS tests, mark 'connection_pooler' as Computed

- CHANGELOG.md
- docs/data-sources/autoscaling_group.md
- docs/data-sources/autoscaling_group_servers.md
- docs/data-sources/dbaas_mongo_template.md
- docs/resources/autoscaling_group.md
- docs/resources/server_boot_device_selection.md
Places some docs under the correct categories on TF registry
> Fx: metadata for docs that are not rendering correctly in TF registry

- CHANGELOG.md
- docs/data-sources/volume.md
- docs/resources/volume.md
- ionoscloud/data_source_volume.go
- ionoscloud/resource_volume.go
`image_alias` it's not returned in the response for a `GET` on volumes, therefore we can't store `image_alias` in the state.
For `ionoscloud_volume` RESOURCE we simply removed the sets related to `image_alias` from the read function.
For `ionoscloud_volume` DATA SOURCE we also removed the `image_alias` from the DS schema. This isn't a breaking change since the field wasn't set before (the `GET` response for the volume doesn't contain info about `image_alias`, so nothing was set, even though the `image_alias` was present in the schema for the DS).
> refactor: Remove 'image_alias' from volume resource/ds

- CHANGELOG.md
- docs/resources/cube_server.md
- docs/resources/server.md
- ionoscloud/import_server_test.go
- ionoscloud/resource_cube_server.go
- ionoscloud/resource_server.go
> feat: add allow_replace to server resource

- CHANGELOG.md
- ionoscloud/resource_cube_server.go
- ionoscloud/resource_server_test.go
- ionoscloud/resource_vcpu_server_test.go
- services/cloudapi/cloudapifirewall/firewall.go
> fix: server an vcpu test, debug logs

- CHANGELOG.md
- docs/data-sources/lan.md
- docs/resources/lan.md
- go.mod
- go.sum
- ionoscloud/data_source_lan.go
- ionoscloud/resource_lan.go
- ionoscloud/resource_lan_test.go
- ionoscloud/test_constants.go
- utils/constant/constants.go
- vendor/github.com/ionos-cloud/sdk-go/v6/client.go
- vendor/github.com/ionos-cloud/sdk-go/v6/configuration.go
- vendor/github.com/ionos-cloud/sdk-go/v6/model_group_properties.go
- vendor/github.com/ionos-cloud/sdk-go/v6/model_lan_properties.go
- vendor/modules.txt
> feat: Add ipv4CIDRBlock attribute for LAN resource & data source

- .github/workflows/dbaas-test-run.yml
Add `inMemoryDB` tag to the list of tests for DBaaS.
> test: Add `inMemoryDB` tag to the list of `DBaaS` periodic tests

- CHANGELOG.md
- ionoscloud/resource_s3_key.go
> fix: add check for 422 response on s3 key not found

- CHANGELOG.md
- services/objectstoragemanagement/accesskeys.go
`canonicalUserId` can be `nil` in the API response when working with object storage access keys. In this case, the provider should not crash. This PR takes care of this: if the value is `nil` then it won't be set in the state.
> fix: Fix provider crash

- services/dns/client.go
During the rebase process for the DNS bundle integration PR: https://github.com/ionos-cloud/terraform-provider-ionoscloud/pull/753, I missed a faulty client initialization that doesn't take into consideration some important values. 
This PR fixes the problem.
> fix: Fix client init for DNS

- CHANGELOG.md
- docs/resources/kafka_cluster.md
- ionoscloud/resource_kafka_cluster.go
- ionoscloud/resource_kafka_topic_test.go
> fix: kafka remove mentions of 3.7.0 as it is no longer supported

- CHANGELOG.md
- ionoscloud/resource_dbaas_pgsql_cluster.go
- ionoscloud/resource_dbaas_pgsql_cluster_test.go
Hopefully, it will fix: https://github.com/ionos-cloud/terraform-provider-ionoscloud/issues/864
> fix: Mark 'allow_replace' as 'Computed' for PgSQL clusters, update tests
