ionos-cloud/terraform-provider-ionoscloud

ionoscloud/data_source_private_crossconnect_test.go, ionoscloud/provider.go, ionoscloud/resource_backup_unit.go, ionoscloud/resource_datacenter.go, ionoscloud/resource_ipfailover.go, ionoscloud/resource_ipfailover_test.go, ionoscloud/resource_k8s_cluster.go, ionoscloud/resource_k8s_node_pool.go, ionoscloud/resource_lan.go, ionoscloud/resource_lan_test.go, ionoscloud/resource_private_crossconnect.go, ionoscloud/resource_s3_key.go, ionoscloud/utils.go
fix: taking into consideration timeout + fixing test engine for ipfailover
=> Timeout + ipfailover test

ionoscloud/resource_volume.go, ionoscloud/resource_volume_test.go
fix: fixes #30 - volume password and bus are not set if they consist of an empty string
=> fix: fixes #30 - volume without password and default value for bus

CHANGELOG.md, ionoscloud/resource_s3_key.go, ionoscloud/resource_s3_key_test.go
See issue-36 for the bug description.
=> fix: correctly setting the active property of the s3 key upon creation

docs/resources/k8s_node_pool.md, ionoscloud/resource_k8s_node_pool.go, ionoscloud/resource_k8s_node_pool_test.go, ionoscloud/resource_lan.go, ionoscloud/resource_server.go, ionoscloud/resource_server_test.go
- fixes #25 correctly set of dhcp - added true as default and replaced terraform getOk function with get
- nil check for nodePoolLan.Routes 
- added firewall_type field in nic entity of server resource
- docs update
- fix #40 ip_failover just computed for lan
=> fix: fixes #25 correctly set of dhcp + nil check +  firewall_type in server

CHANGELOG.md, docs/resources/nic.md, docs/resources/server.md, ionoscloud/resource_nic.go, ionoscloud/resource_nic_test.go, ionoscloud/resource_server.go, ionoscloud/resource_server_test.go
=> fix: fixes #47 - corrected nic resource to accept a list of strings for ips

CHANGELOG.md, docs/resources/k8s_node_pool.md, ionoscloud/resource_k8s_node_pool.go, ionoscloud/resource_k8s_node_pool_test.go
fix: fixes #71 - - recreate nodepool on change of specifications
_Write an `x` in the boxes that apply._
[x] Tests added or updated
[x] Documentation updated
[x] Changelog updated and version incremented
[x] Github Issue linked if any
=> fix: fixes #71 recreate nodepool on change of specifications

CHANGELOG.md, docs/resources/k8s_node_pool.md, ionoscloud/resource_k8s_node_pool.go, ionoscloud/resource_k8s_node_pool_test.go, ionoscloud/utils.go
fix: fixes #77 import for k8s nodepool with nil check
rollback to the node pool behaviour before the fix of issue #71
_Write an `x` in the boxes that apply._
[x] Tests added or updated
[x] Documentation updated
[x] Changelog updated and version incremented
[x] Github Issue linked if any
=> fix: fixes #77 import for k8s nodepool with nil check

CHANGELOG.md, ionoscloud/data_source_datacenter.go, ionoscloud/data_source_image.go, ionoscloud/data_source_k8s_cluster.go, ionoscloud/data_source_k8s_node_pool.go, ionoscloud/data_source_lan.go, ionoscloud/data_source_private_crossconnect.go, ionoscloud/data_source_server.go, ionoscloud/resource_datacenter.go, ionoscloud/resource_ipblock.go, ionoscloud/resource_k8s_cluster.go, ionoscloud/resource_k8s_node_pool.go, ionoscloud/resource_nic.go, ionoscloud/resource_private_crossconnect.go, ionoscloud/resource_server.go, ionoscloud/resource_volume.go
Fixed set of empty array in terraform state instead of null by doing the following: 
- verified length in read functions
- replaced slice := make([]type, n,n) with var slice []type in order not to allocate memory and  have an empty slice
- did the above actions for all files to avoid similar problems in the future
=> fixed set of empty array in terraform state instead of null

CHANGELOG.md, docs/index.md
Added documentation entry for debug usage.
=> Added entry for debug usage and set code block parser

CHANGELOG.md, ionoscloud/data_source_k8s_node_pool.go, ionoscloud/resource_k8s_node_pool.go, ionoscloud/utils.go
Fixes k8s node pool import when it comes to reading private lans.
=> correctly importing private lans from k8s node pools

ionoscloud/resource_k8s_node_pool_test.go
Updated basic test for k8s node pool to include lans
=> updated test for node pool lans

CHANGELOG.md, docs/data-sources/s3_key.md, ionoscloud/data_source_s3_key.go, ionoscloud/data_source_s3_key_test.go, ionoscloud/import_s3_keys_test.go, ionoscloud/provider.go, ionoscloud/resource_s3_key.go, ionoscloud/resource_s3_key_test.go, ionoscloud/utils.go
=> SDK-475 add s3 key data source

CHANGELOG.md, docs/resources/k8s_node_pool.md, ionoscloud/resource_k8s_node_pool.go, ionoscloud/resource_k8s_node_pool_test.go, ionoscloud/utils.go
Added location and labels fields to k8s nodepool.
- [ X] Tests added or updated
- [ X] Documentation updated
- [ X] Changelog updated and version incremented
=> Sdk 408 k8s add nodepool and annotations

CHANGELOG.md, docs/data-sources/datacenter.md, docs/data-sources/ipblock.md, ionoscloud/constants.go, ionoscloud/data_source_ipblock.go, ionoscloud/data_source_ipblock_test.go, ionoscloud/import_ipblock_test.go, ionoscloud/provider.go, ionoscloud/resource_ipblock.go, ionoscloud/resource_ipblock_test.go
Add ipblock data source and import
=> SDK-514 Add ip block data source and import

docs/data-sources/ipblock.md
Better doc for ip block data source
- [X ] Documentation updated
=> SDK-389 Betters docs for data source

CHANGELOG.md, docs/data-sources/nic.md, docs/resources/nic.md, ionoscloud/constants.go, ionoscloud/data_source_nic.go, ionoscloud/data_source_nic_test.go, ionoscloud/import_nic_test.go, ionoscloud/provider.go, ionoscloud/resource_nic.go, ionoscloud/resource_nic_test.go, ionoscloud/utils.go
Add data source for NIC and fix import that was nor working.
=> Sdk 552 v6 add nic datasource and fix import

CHANGELOG.md, docs/data-sources/nic.md, docs/resources/nic.md, ionoscloud/constants.go, ionoscloud/data_source_nic.go, ionoscloud/data_source_nic_test.go, ionoscloud/import_nic_test.go, ionoscloud/provider.go, ionoscloud/resource_ipblock.go, ionoscloud/resource_nic.go, ionoscloud/resource_nic_test.go, ionoscloud/utils.go
Add nic data source and fix import.
=> SDK-522 Add nic datasource and fix import 

CHANGELOG.md, docs/data-sources/share.md, ionoscloud/constants.go, ionoscloud/data_source_share.go, ionoscloud/data_source_share_test.go, ionoscloud/import_share_test.go, ionoscloud/provider.go, ionoscloud/resource_ipblock.go, ionoscloud/resource_nic.go, ionoscloud/resource_nic_test.go, ionoscloud/resource_s3_key.go, ionoscloud/resource_share.go, ionoscloud/resource_share_test.go, ionoscloud/utils.go
=> SDK-552 Add share datasource

CHANGELOG.md, ionoscloud/data_source_nic.go, ionoscloud/resource_ipblock.go, ionoscloud/resource_loadbalancer.go, ionoscloud/resource_share.go, ionoscloud/resource_volume.go
Prevent plugin crash and add some additional logs
=> fix: Prevent terraform crash and add additional logs

CHANGELOG.md, docs/resources/k8s_node_pool.md, ionoscloud/resource_k8s_cluster_test.go, ionoscloud/resource_k8s_node_pool.go, vendor/github.com/ionos-cloud/sdk-go/v6/sonar-project.properties, vendor/modules.txt
fixed #155: added stateUpgrader for handling change of lan field structure
=> fixed #155: added stateUpgrader for handling change of lan field structure

CHANGELOG.md, ionoscloud/resource_k8s_node_pool.go, ionoscloud/resource_k8s_node_pool_test.go
=> fixed SDK-640

.github/pull_request_template.md, CHANGELOG.md, README.md, docs/index.md
Made the following changes to docs: 
- improved index.md for terraform registry with a more detailed description of environment and terraform variables
- added badges containing the release and go version in README.md
- improved PR template according to confluence
=> docs: added badges, improved env variables description and PR template

CHANGELOG.md, README.md, gitbook_docs/README.md, go.mod, main.go
Add v5 to allow importing module in other programs.
Add note to documentation on using v6 from now on.
=> fix/doc: Add versioning to go.mod. Add note on using v6 to Readme.md.

CHANGELOG.md, ionoscloud/config.go, ionoscloud/provider.go
Modify userAgent string:
terraform-provider/<version>_ionos-cloud-sdk-go/<version>_hashicorp-terraform/<version>_terraform-plugin-sdk/<version>_os/<os_type>_arch/<arch>
=> fix: modify userAgent string

CHANGELOG.md, ionoscloud/config.go, ionoscloud/provider.go
V6 UserAgent string new structure
=> fix: v6 modify userAgent string

CHANGELOG.md, ionoscloud/data_source_image_test.go, ionoscloud/data_source_location_test.go, ionoscloud/data_source_resource_test.go, ionoscloud/resource_group_test.go, ionoscloud/resource_lan.go, ionoscloud/resource_lan_test.go, ionoscloud/resource_loadbalancer_test.go, ionoscloud/resource_snapshot_test.go
fix: fixed lan deletion - wait for completion of nic deletion
=> fix: fixed lan deletion - wait for completion of nic deletion

.github/workflows/test.yml
Add log option and branch for test workflow
=> Test: modify test workflow

CHANGELOG.md, docs/resources/dbaas_pgsql_cluster.md, services/dbaas/cluster.go
- bug fix when there is not provided a maintenance window for dbaas cluster
- docs improvement with cidr example
=> fix: bug fix on not setting the maintenance window on dbaas cluster and docs update

CHANGELOG.md, ionoscloud/provider.go
Update http client with better values.
=> feat: update http client for cloudapi

CHANGELOG.md, ionoscloud/provider.go
Improve performance and behaviour of http client. Port from master/v6.
=> feat: update http client

ionoscloud/resource_networkloadbalancer_forwardingrule.go
Health_check can be empty/mising, as it is an optional block. If it is empty do not do anything.
Note: still to fix, supress diff for health_check if it is computed.
=> fix: check for health_check length

CHANGELOG.md, docs/data-sources/k8s_cluster.md
Update doc of how to dump kube_config into a file in yaml format.
=> doc: update doc on how to dump cube config into file in yaml format

.github/workflows/test.yml, README.md
Change workflow name to 'Test suite'
=> fix: update test workflow name

docs/data-sources/ipblock.md, gitbook_docs/summary.md
- added documentantion to gitbook
=> docs: added documentation files to gitbook

docs/data-sources/backup_unit.md, docs/data-sources/datacenter.md, docs/data-sources/dbaas_pgsql_backups.md, docs/data-sources/dbaas_pgsql_cluster.md, docs/data-sources/dbaas_pgsql_versions.md, docs/data-sources/firewall.md, docs/data-sources/group.md, docs/data-sources/image.md, docs/data-sources/ipblock.md, docs/data-sources/ipfailover.md, docs/data-sources/k8s_cluster.md, docs/data-sources/k8s_node_pool.md, docs/data-sources/lan.md, docs/data-sources/location.md, docs/data-sources/natgateway.md, docs/data-sources/natgateway_rule.md, docs/data-sources/networkloadbalancer.md, docs/data-sources/networkloadbalancer_forwardingrule.md, docs/data-sources/nic.md, docs/data-sources/private_crossconnect.md, docs/data-sources/resource.md, docs/data-sources/s3_key.md, docs/data-sources/server.md, docs/data-sources/share.md, docs/data-sources/snapshot.md, docs/data-sources/template.md, docs/data-sources/user.md, docs/data-sources/volume.md
Adds some details to datasource documentation.
=> doc: small fixes to data source descriptions

CHANGELOG.md, docs/resources/k8s_node_pool.md
Improve doc for allow_replace field in node pool resource
=> doc: improve text for allow_replace field in node pool resource

docs/data-sources/datacenter.md, docs/resources/server.md
=> docs: example fix

README.md, gitbook_docs/README.md, gitbook_docs/summary.md
=> docs: duplicated README to remove git badges

docs/resources/group.md, docs/resources/loadbalancer.md, docs/resources/server.md, ionoscloud/provider.go, ionoscloud/resource_user_test.go, ionoscloud/utils.go
- Add links to some doc sections
- Add logs in case of nil path error
=> doc: add links to doc and some logs to provider

CHANGELOG.md, docs/index.md, docs/resources/ipfailover.md, examples/ip_failover/README.md, examples/ip_failover/initial_infrastructure/main.tf, examples/ip_failover/update_nic/main.tf
Solves issue #241 and issue #235
=> doc: update version and example in index.md + added example for multiple NICs on an IP Failover

CHANGELOG.md, docs/index.md, docs/resources/ipfailover.md, examples/ip_failover/README.md, examples/ip_failover/initial_infrastructure/main.tf, examples/ip_failover/update_nic/main.tf
Solves issue #241 and issue #235
=> docs: update version and example in index.md + added example for multiple NICs on an IP Failover

ionoscloud/resource_datacenter_test.go, ionoscloud/test_constants.go
Fix k8s test compilation when running with tags.
=> fix: fix k8s tests compilation

.github/workflows/daily-test-run.yml, ionoscloud/resource_server_test.go, ionoscloud/resource_volume_test.go, ionoscloud/test_constants.go
- Fix image-name tests.
- Test workflow will now run at 09:00 AM.
=> fix: fix image_name tests and change time when the workflow runs

ionoscloud/import_s3_keys_test.go
Fix s3 key import test that sometimes fails.
=> fix: s3 key import test

CHANGELOG.md, docs/resources/group.md, ionoscloud/resource_group.go, ionoscloud/resource_group_test.go
=> fix: reintroduce user_id

README.md
=> doc: add daily test badge run

GNUmakefile, README.md
- Fix running tests using makefile
- Add details about tags in Readme
- Update go version used to build provider
=> fix: makefile tests and add to readme

CHANGELOG.md, go.mod, ionoscloud/data_source_dbaas_pgsql_cluster.go, ionoscloud/data_source_k8s_cluster.go, ionoscloud/data_source_natgateway.go, ionoscloud/data_source_natgateway_rule.go, ionoscloud/data_source_networkloadbalancer.go, ionoscloud/data_source_networkloadbalancer_forwardingrule.go, ionoscloud/import_dbaas_pgsql_cluster_test.go, ionoscloud/resource_dbaas_pgsql_cluster_test.go, ionoscloud/resource_k8s_cluster_test.go, ionoscloud/resource_k8s_node_pool_test.go, ionoscloud/resource_lan.go, ionoscloud/resource_natgateway.go, ionoscloud/resource_natgateway_test.go, utils/utils.go
=> fix: fixed cluster data_source

CHANGELOG.md, ionoscloud/provider.go, ionoscloud/provider_test.go
=> enhancement: IONOS_USERNAME, IONOS_PASSWORD and IONOS_TOKEN can be set in the same time

CHANGELOG.md, docs/data-sources/dbaas_pgsql_cluster.md, docs/resources/dbaas_pgsql_cluster.md, go.mod, ionoscloud/data_source_dbaas_pgsql_cluster.go, ionoscloud/import_dbaas_pgsql_cluster_test.go, ionoscloud/resource_dbaas_pgsql_cluster.go, ionoscloud/resource_dbaas_pgsql_cluster_test.go, ionoscloud/resource_k8s_cluster_test.go, ionoscloud/resource_lan.go, services/dbaas/cluster.go
=> feat: added backup_location to dbaas

CHANGELOG.md, README.md
=> doc: improved README.md testing info

CHANGELOG.md, ionoscloud/resource_dbaas_pgsql_cluster.go, ionoscloud/resource_dbaas_pgsql_cluster_test.go, ionoscloud/resource_server.go
- type field on server should be case insensitive
- fix dbaas test, to be able to delete lan after removing connection
=> fix: dbaas test and type should be case insensitive

ionoscloud/resource_natgateway_test.go
=> fix: natgateway test

CHANGELOG.md, ionoscloud/resource_k8s_node_pool.go
fixed bug when upgrading from a v6.0.0-beta.X version to a stable one (number is required error)
=> fix: bug when upgrading from a v6.0.0-beta.X version to a stable one 

ionoscloud/data_source_servers_test.go
=> fix: servers tests

ionoscloud/resource_nic_test.go
=> fix: daily nic import test

docs/resources/k8s_cluster.md
fixes #292 
Remove `public` field from k8s cluster doc example.
=> doc: remove public field from doc example

CHANGELOG.md, docs/data-sources/user.md, ionoscloud/data_source_user.go
if the user does not provide any arguments for user data-source, try to use the email from client configuration (if provided) 
_note: no tests added since they will fail due to not being able to destroy the admin user_
=> feat: take current user for the user data source 

ionoscloud/data_source_servers.go, ionoscloud/resource_nic.go, ionoscloud/resource_server.go, ionoscloud/resource_volume.go
Fixes a problem with the internal server nic creation.
Splits server creation into multiple functions.
=> fix: refactor server code

ionoscloud/resource_volume.go
=> fix: refactor volume creation

ionoscloud/resource_server.go
=> fix: add back nicId

.github/workflows/daily-test-run.yml, ionoscloud/resource_nic.go
Fix workflow and add info msg.
=> fix: test workflow and add warning to lan not found

CHANGELOG.md, docs/data-sources/volume.md, docs/resources/server.md, docs/resources/volume.md, ionoscloud/resource_server.go, ionoscloud/resource_server_test.go, ionoscloud/test_constants.go, utils/utils.go
Allow ssh_key_path to receive keys directly, not only as path.
Fixes : #307
=> Feat: allow ssh keys directly in ssh key path

ionoscloud/provider.go
=> fix: mongo client init

ionoscloud/resource_backup_unit.go, ionoscloud/resource_dbaas_pgsql_cluster.go, ionoscloud/resource_lan.go, ionoscloud/resource_private_crossconnect.go, ionoscloud/resource_snapshot.go, utils/constants.go
Available state needs to be uppercase or to not take case into consideration when checking.
=> fix: AVAILABLE instead of Available

README.md, docs/index.md
Update the READMEs to reflect the new changes and to add a little bit more clarity for the users.
=> doc: update READMEs

.github/workflows/k8s-test-run.yml
=> test: add workflow for weekly k8s tests

.github/workflows/k8s-test-run.yml
Follow up for [this](https://github.com/ionos-cloud/terraform-provider-ionoscloud/pull/329/files#r1005645774) comment.
=> doc: modify hour for periodic k8s tests

CHANGELOG.md, ionoscloud/resource_k8s_cluster.go, ionoscloud/resource_k8s_cluster_test.go
=> fix: issue #326, delete empty volume

ionoscloud/constants.go, ionoscloud/resource_user.go, ionoscloud/resource_user_test.go
Fixing https://jira.sso.ionos.cloud/browse/SDK-1204.
=> fix: fix user creation bug

.github/workflows/build.yml, ionoscloud/constants.go, ionoscloud/data_source_dbaas_mongo_cluster.go, ionoscloud/data_source_nic_test.go, ionoscloud/data_source_servers.go, ionoscloud/resource_dbaas_mongodb_cluster.go, ionoscloud/resource_s3_key_test.go, ionoscloud/resource_volume_test.go, ionoscloud/testUtil.go, ionoscloud/utils.go
Run fmt every workflow.
Fix existent format issues.
=> fix: spaces, add fmt step to build workflow

CHANGELOG.md
=> doc: update CHANGELOG with information about the latest fix

CHANGELOG.md, docs/data-sources/server.md, docs/resources/server.md, ionoscloud/data_source_server.go, ionoscloud/data_source_servers.go, ionoscloud/data_source_servers_test.go, ionoscloud/import_server_test.go, ionoscloud/labels_service.go, ionoscloud/provider_test.go, ionoscloud/resource_server.go, ionoscloud/resource_server_test.go, ionoscloud/test_constants.go, ionoscloud/utils.go
Jira issue: https://jira.sso.ionos.cloud/browse/SDK-1071
=> feat: implement functionality for server labels

CHANGELOG.md, docs/data-sources/dbaas_mongo_template.md, ionoscloud/constants.go, ionoscloud/data_source_dbaas_mongo_template.go, ionoscloud/data_source_dbaas_mongo_template_test.go, ionoscloud/provider.go, ionoscloud/test_constants.go, services/dbaas/cluster.go
=> feat: add DBaaS Mongo Template data source

ionoscloud/data_source_container_registry_token.go, ionoscloud/data_source_dbaas_mongo_cluster.go, ionoscloud/data_source_dbaas_pgsql_cluster.go, ionoscloud/data_source_firewall.go, ionoscloud/data_source_group.go, ionoscloud/data_source_k8s_cluster.go, ionoscloud/data_source_k8s_node_pool.go, ionoscloud/data_source_natgateway_rule.go, ionoscloud/data_source_networkloadbalancer_forwardingrule.go, ionoscloud/data_source_private_crossconnect.go, ionoscloud/data_source_snapshot.go, ionoscloud/data_source_target_group.go, ionoscloud/resource_backup_unit.go, ionoscloud/resource_backup_unit_test.go, ionoscloud/resource_certificate_manager_test.go, ionoscloud/resource_dbaas_mongodb_cluster.go, ionoscloud/resource_dbaas_pgsql_cluster.go, ionoscloud/resource_k8s_node_pool.go, ionoscloud/resource_loadbalancer.go, ionoscloud/resource_loadbalancer_test.go, ionoscloud/resource_s3_key.go, ionoscloud/resource_server.go, ionoscloud/resource_share_test.go, ionoscloud/resource_volume.go
Get nic id from first element in entities, if lan 1 not found.
Fix %w in printf
=> fix: get nic id from entities and %w fix in printf

ionoscloud/data_source_dbaas_mongo_template_test.go
=> test: add tags for DBaaS Mongo templates tests

ionoscloud/resource_group.go
=> fix: fix typo in group resource

docs/data-sources/volume.md, docs/resources/volume.md
=> doc: update documentation for volumes

docs/resources/server.md, services/dbaas/backups.go, services/dbaas/cluster.go, services/dbaas/versions.go
Remove useless checks from services and fix typo in server documentation.
=> refactor: remove useless checks from services

.github/workflows/compute-test-run.yml, .github/workflows/dbaas-test-run.yml, .github/workflows/k8s-test-run.yml, ionoscloud/resource_dbaas_mongodb_cluster.go
Test workflows will run once a week.
=> fix: run test workflows once a week

CHANGELOG.md, docs/data-sources/image.md, ionoscloud/data_source_image.go, ionoscloud/data_source_image_test.go
Add option to search for an image using image_alias
Improve documentation and errors.
=> feat: add option to search for an image using image_alias

go.mod, go.sum, vendor/github.com/ionos-cloud/sdk-go-dbaas-postgres/api_backups.go, vendor/github.com/ionos-cloud/sdk-go-dbaas-postgres/api_clusters.go, vendor/github.com/ionos-cloud/sdk-go-dbaas-postgres/client.go, vendor/github.com/ionos-cloud/sdk-go-dbaas-postgres/configuration.go, vendor/github.com/ionos-cloud/sdk-go-dbaas-postgres/model_cluster_backup_list.go, vendor/github.com/ionos-cloud/sdk-go-dbaas-postgres/model_cluster_list.go, vendor/github.com/ionos-cloud/sdk-go-dbaas-postgres/model_pagination.go, vendor/github.com/ionos-cloud/sdk-go-dbaas-postgres/model_pagination_links.go, vendor/github.com/ionos-cloud/sdk-go-dbaas-postgres/model_state.go, vendor/github.com/ionos-cloud/sdk-go-dbaas-postgres/utils.go, vendor/modules.txt
=> feat: update DBaaS PostgreSQL SDK version

docs/data-sources/certificate.md, docs/resources/certificate.md
Fix typo in documentation for Certificate Manager.
=> doc: fix typo in documentation

.github/workflows/test.yml
=> test: Add IONOS_TOKEN env var for tests

ionoscloud/import_server_test.go
=> test: Fix server import tests

ionoscloud/data_source_image_test.go
=> test: fix data source image test

.github/workflows/issues.yml
Fixes: 
[variable](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable)
https://github.com/orgs/community/discussions/27065#discussioncomment-3798970
=> fix: vulnerability of sanitizing issue title

CHANGELOG.md, ionoscloud/resource_server.go
=> fix: fix inline_volume_ids upgrade

CHANGELOG.md, ionoscloud/labels_service.go
Add validation to label keys and values.
Fixes label issue in #404
=> fix: add validation to labels in terraform

docs/data-sources/dns_record.md, docs/data-sources/dns_zone.md, docs/resources/dns_record.md, docs/resources/dns_zone.md
Rename DNS in the documentation to Cloud DNS.
=> doc: rename to Cloud DNS

gitbook_docs/data-sources-header.md, gitbook_docs/resources-header.md, gitbook_docs/summary.md
Additional fix for the changes in PR #408. Also removed unused md files.
=> docs: fix gitbook references

CHANGELOG.md, docs/resources/private_crossconnect.md
Improve example for ionoscloud_private_crossconnect.
=> doc: improve example for ionoscloud_private_crossconnect

README.md, gitbook_docs/README.md
=> docs: update End of Life notice

CHANGELOG.md
=> doc: update documentation

ionoscloud/data_source_dbaas_mongo_template_test.go
Failed pipeline: https://github.com/ionos-cloud/terraform-provider-ionoscloud/actions/runs/5585447606/job/15126176440
=> test: Fix tests for Mongo templates

.github/workflows/test.yml, ionoscloud/resource_logging_pipeline_test.go
=> test: add tag for Logging Service tests

ionoscloud/import_application_loadbalancer_forwardingrule_test.go, ionoscloud/import_application_loadbalancer_test.go, ionoscloud/import_natgateway_rule_test.go, ionoscloud/import_natgateway_test.go, ionoscloud/import_networkloadbalancer_forwardingrule_test.go, ionoscloud/import_networkloadbalancer_test.go, ionoscloud/resource_application_loadbalancer_forwardingrule_test.go, ionoscloud/resource_application_loadbalancer_test.go, ionoscloud/resource_natgateway_rule_test.go, ionoscloud/resource_natgateway_test.go, ionoscloud/resource_networkloadbalancer_forwardingrule_test.go, ionoscloud/resource_networkloadbalancer_test.go
There are some problems with some APIs, delayed requests, big queues etc, so for now we need to avoid those specific tests. For now, I'm removing the `all` tag for the faulty files in order to avoid including them if we want to run all the tests.
=> test: remove 'all' tag for some faulty tests [skip actions]

ionoscloud/test_constants.go
Fixed [this](https://github.com/ionos-cloud/terraform-provider-ionoscloud/actions/runs/5712738138) pipeline.
=> test: Fix k8s tests

ionoscloud/resource_server_cube_test.go, ionoscloud/test_constants.go
=> fix: cube server tests

ionoscloud/resource_server_cube_test.go
=> fix: TestAccCubeServerWithICMP

CHANGELOG.md, docs/data-sources/image.md, docs/resources/cube_server.md, docs/resources/server.md, ionoscloud/resource_server.go
=> fix: boot_cdrom crash and add better documentation

docs/data-sources/dataplatform_cluster.md, docs/resources/dataplatform_cluster.md, docs/resources/dataplatform_node_pool.md, utils/constant/constants.go
Updates the default DataPlatformVersion to the required minimum: 23.4
=> fix: update DataPlatformVersion

ionoscloud/resource_server_test.go
=> fix: change to existing cdrom id

CHANGELOG.md, ionoscloud/resource_server.go, ionoscloud/resource_server_vcpu.go, ionoscloud/resource_volume.go
=> fix: ssh_keys problems on upgrade or creation

.github/workflows/server-test-run.yml, ionoscloud/data_source_servers_test.go
Run workflow with `server` tag Monday, Wednesday and Friday at 11:00.
=> feat: add workflow for server tag to run every MON WED FRI

ionoscloud/data_source_nic_test.go
=> fix: ipv6CidrBlock should pe string

ionoscloud/resource_k8s_cluster_test.go, ionoscloud/test_constants.go
=> fix: tests k8s bucket and k8s version

CHANGELOG.md, README.md, docs/index.md, gitbook_docs/README.md, go.mod, go.sum, vendor/github.com/ionos-cloud/sdk-go/v6/README.md, vendor/github.com/ionos-cloud/sdk-go/v6/client.go, vendor/github.com/ionos-cloud/sdk-go/v6/configuration.go, vendor/modules.txt
=> feat: update go sdk to allow contract number to be used

CHANGELOG.md, docs/index.md, ionoscloud/provider.go
=> feature: allow account_number to be set in provider config

CHANGELOG.md, docs/resources/ipfailover.md, internal/uuidgen/uuidgen.go, ionoscloud/data_source_ipfailover.go, ionoscloud/import_ipfailover_test.go, ionoscloud/resource_ipfailover.go, ionoscloud/resource_ipfailover_test.go, services/cloudapi/lanSvc/lan.go, utils/constant/constants.go
Rewrite some of the methods for IP Failover resource and data source since the functionality was not correct for them.
=> fix: fix IP Failover resource

CHANGELOG.md
=> doc: modify CHANGELOG.md

ionoscloud/resource_ipfailover.go, services/cloudapi/cloudapilan/lan.go
=> refactor: rename LAN service

CHANGELOG.md, main.go
=> chore: replace deprecated function for debugging

CHANGELOG.md, ionoscloud/resource_server.go, ionoscloud/resource_server_cube.go, ionoscloud/resource_server_test.go, ionoscloud/resource_server_vcpu.go, ionoscloud/resource_server_vcpu_test.go, ionoscloud/test_constants.go, services/cloudapi/cloudapiserver/server.go
=> power state for vcpu servers

CHANGELOG.md, ionoscloud/data_source_nic.go, services/cloudapi/cloudapinic/nic.go
=> fix: nil deref on nic datasource

CHANGELOG.md, docs/data-sources/nic.md, docs/resources/nic.md, ionoscloud/data_source_nic.go, ionoscloud/resource_nic.go, ionoscloud/resource_nic_test.go, services/cloudapi/cloudapinic/nic.go, services/cloudapi/flowlog/flowlog.go, utils/constant/constants.go, utils/utils.go
=> feat: add flowlog to nic

CHANGELOG.md, docs/data-sources/networkloadbalancer.md, docs/resources/networkloadbalancer.md, docs/resources/nic.md, ionoscloud/data_source_networkloadbalancer.go, ionoscloud/resource_networkloadbalancer.go, ionoscloud/resource_networkloadbalancer_test.go, ionoscloud/resource_nic.go, services/cloudapi/flowlog/flowlog.go
=> feat: add flowlog to networkloadbalancer

docs/data-sources/dataplatform_cluster.md, docs/resources/dataplatform_cluster.md, docs/resources/dataplatform_node_pool.md, utils/constant/constants.go
=> fix: replace with new dataplatform version

CHANGELOG.md, ionoscloud/resource_server.go
=> fix: crash when server import without inline nic

.gitignore, CHANGELOG.md, docs/data-sources/application_loadbalancer.md, docs/resources/application_loadbalancer.md, ionoscloud/data_source_application_loadbalancer.go, ionoscloud/resource_application_loadbalancer.go, ionoscloud/resource_application_loadbalancer_test.go, ionoscloud/resource_firewall.go, ionoscloud/resource_nic.go, services/cloudapi/flowlog/flowlog.go
=> feat: add flowlog to alb

ionoscloud/data_source_autoscaling_group.go, ionoscloud/data_source_autoscaling_group_servers.go, ionoscloud/resource_autoscaling_group.go, ionoscloud/resource_autoscaling_group_test.go, services/autoscaling/groups.go
Allows updates to multiple volumes as the index is not fixed.
Make image_password sensitive
Get function takes a parameter
=> fix: make volume a set and image_password sensitive

docs/data-sources/group.md, docs/data-sources/user.md
Fixes this issue: https://github.com/ionos-cloud/terraform-provider-ionoscloud/issues/492
=> doc: Fix copy/paste mistake in data sources user and group.

CHANGELOG.md, ionoscloud/data_source_dns_record.go, services/dns/record.go
=> fix: allow empty dns record name

CHANGELOG.md, ionoscloud/resource_application_loadbalancer.go, ionoscloud/resource_application_loadbalancer_forwardingrule.go, ionoscloud/resource_datacenter.go, ionoscloud/resource_firewall.go, ionoscloud/resource_group.go, ionoscloud/resource_ipblock.go, ionoscloud/resource_ipfailover.go, ionoscloud/resource_lan.go, ionoscloud/resource_loadbalancer.go, ionoscloud/resource_natgateway.go, ionoscloud/resource_natgateway_rule.go, ionoscloud/resource_networkloadbalancer.go, ionoscloud/resource_networkloadbalancer_forwardingrule.go, ionoscloud/resource_s3_key.go, ionoscloud/resource_server.go, ionoscloud/resource_server_cube.go, ionoscloud/resource_share.go, ionoscloud/resource_snapshot.go, ionoscloud/resource_target_group.go, ionoscloud/resource_user.go, ionoscloud/resource_volume.go, services/cloudapi/cloudapifirewall/firewall.go, services/cloudapi/cloudapinic/nic.go, services/cloudapi/cloudapiserver/server.go, services/cloudapi/state.go
=> feat: use location instead of get header

.github/workflows/linter.yaml
=> add dummy linter ci

docs/resources/dbaas_mongo_user.md
=> doc: fix documentation for DBaaS Mongo User

CHANGELOG.md, ionoscloud/provider.go
=> feat: modify default timeout for k8s nodepools

ionoscloud/import_k8s_cluster_test.go
=> test: Fix k8s clusters import test

CHANGELOG.md, ionoscloud/provider.go, ionoscloud/resource_k8s_node_pool.go, utils/constant/constants.go
=> fix: increase timeout to 3 hours for nodepools

CHANGELOG.md, ionoscloud/resource_dbaas_mongodb_cluster.go, ionoscloud/resource_dbaas_mongodb_cluster_test.go
=> fix: remove credentials from mongo clusters resource

.golangci.yml, CHANGELOG.md, docs/data-sources/k8_clusters.md, ionoscloud/data_source_k8s_cluster.go, ionoscloud/data_source_k8s_clusters.go, ionoscloud/provider.go, ionoscloud/resource_k8s_cluster_test.go, ionoscloud/test_constants.go, utils/constant/constants.go, utils/utils.go
Data source for retrieving a list of k8s clusters which match filtering criteria.
=> feat: k8s clusters data source

CHANGELOG.md, docs/data-sources/k8_clusters.md, docs/data-sources/servers.md, ionoscloud/data_source_k8s_clusters.go, ionoscloud/data_source_servers.go, ionoscloud/resource_k8s_cluster_test.go, ionoscloud/resource_k8s_node_pool.go
=> fix: filters should be optional for servers and clusters datasources

CHANGELOG.md, docs/resources/dbaas_mongo_cluster.md, docs/resources/dbaas_pgsql_cluster.md, ionoscloud/resource_dbaas_mongodb_cluster.go, ionoscloud/resource_dbaas_pgsql_cluster.go
=> doc: pgsql and mongo cluster doc

ionoscloud/test_constants.go
Fix https://github.com/ionos-cloud/terraform-provider-ionoscloud/actions/runs/8230155657
=> test: Fix k8s tests by modifying name for k8s bucket

.github/workflows/k8s-test-run.yml
=> refactor: Modify k8s workflow

CHANGELOG.md, docs/data-sources/dbaas_mariadb_backups.md, docs/data-sources/dbaas_mariadb_cluster.md, docs/resources/dbaas_mariadb_cluster.md, gitbook_docs/summary.md, ionoscloud/data_source_dbaas_mariadb_backups.go, ionoscloud/data_source_dbaas_mariadb_cluster.go, ionoscloud/provider.go, ionoscloud/resource_dbaas_mariadb_cluster.go, ionoscloud/resource_dbaas_mariadb_cluster_test.go, ionoscloud/resource_dbaas_pgsql_cluster_test.go, ionoscloud/test_constants.go, services/clients.go, services/containerregistry/client.go, services/dataplatform/client.go, services/dbaas/backups.go, services/dbaas/client.go, services/dbaas/cluster.go, services/dbaas/mariadb/backups.go, services/dbaas/mariadb/client.go, services/dbaas/mariadb/cluster.go, utils/constant/constants.go
=> feat: Add support for MariaDB, add tests and docs

CHANGELOG.md
=> doc: Fix CHANGELOG.md

CHANGELOG.md, ionoscloud/data_source_ipblock.go, ionoscloud/data_source_target_group.go, ionoscloud/data_source_user.go, utils/constant/constants.go
=> fix: Fix pagination issues for target groups, users and IP blocks

.github/workflows/compute-test-run.yml, .github/workflows/dbaas-test-run.yml, .github/workflows/k8s-test-run.yml, .github/workflows/server-test-run.yml, .github/workflows/test.yml
1. Add `IONOS_TOKEN` for all the workflows.
2. Update the description for `Test suite` workflow in order to include some `DBaaS` tags that were missing.
=> feat: Add IONOS_TOKEN for all workflows

.github/workflows/compute-test-run.yml, .github/workflows/dbaas-test-run.yml, .github/workflows/k8s-test-run.yml, .github/workflows/server-test-run.yml
Temporarily deactivate weekly tests since the pipelines are failing with known problems. For now there is no point in running them. After fixing the tests, we can run these again.
=> test: Temporarily deactivate weekly tests

CHANGELOG.md, ionoscloud/resource_dbaas_mongodb_cluster_test.go
=> test: Change location for MongoDB tests to improve running time

CHANGELOG.md, ionoscloud/resource_dbaas_pgsql_cluster_test.go, ionoscloud/resource_dbaas_pgsql_user_test.go
=> test: Fix tests for PgSQL

CHANGELOG.md, docs/resources/dbaas_mongo_user.md, ionoscloud/resource_dbaas_mongodb_user.go
=> fix: Fix MongoDB user import

CHANGELOG.md, docs/data-sources/application_loadbalancer_forwardingrule.md, docs/data-sources/k8s_node_pool.md, docs/data-sources/user.md, docs/resources/application_loadbalancer_forwardingrule.md, docs/resources/k8s_node_pool.md, docs/resources/server.md, docs/resources/user.md, ionoscloud/resource_user.go
Improve user.md descriptions.
Try to fix nested lists to show properly on terraform registry.
=> doc: fix nested lists and improve user descriptions

.golangci.yml, CHANGELOG.md, docs/resources/snapshot.md, ionoscloud/resource_datacenter.go, ionoscloud/resource_server.go, ionoscloud/resource_share_test.go, ionoscloud/resource_snapshot.go, ionoscloud/resource_snapshot_test.go, ionoscloud/test_constants.go
=> feat: new configurable fields to snapshot

CHANGELOG.md, docs/data-sources/image.md, docs/resources/lan.md, docs/resources/server.md, docs/resources/volume.md
=> doc: Fix documentation issues

CHANGELOG.md, docs/data-sources/logging_pipeline.md, docs/resources/logging_pipeline.md, ionoscloud/data_source_logging_pipeline.go, ionoscloud/resource_logging_pipeline.go, ionoscloud/resource_logging_pipeline_test.go, ionoscloud/test_constants.go, services/logging/pipeline.go
Solves https://github.com/ionos-cloud/terraform-provider-ionoscloud/issues/556
=> feat: Add 'grafana_address' attribute for logging pipelines

CHANGELOG.md, docs/data-sources/dns_record.md, docs/data-sources/dns_zone.md, docs/data-sources/logging_pipeline.md, docs/resources/dns_record.md, docs/resources/dns_zone.md, docs/resources/logging_pipeline.md
=> docs: fix #562 - logging and dns accept only tokens for auth

ionoscloud/provider.go, ionoscloud/resource_networksecuritygroup.go, ionoscloud/resource_nsg_firewallrule.go, utils/constant/constants.go
=> Nsg firewallrule resource

ionoscloud/data_source_dbaas_redisdb_replicaset.go, ionoscloud/provider.go, services/dbaas/redisdb/replica_set.go
Add Redis Replicaset datasource
=> feat: redis replica datasource

.github/workflows/release.yml, CHANGELOG.md
=> Fix: Release workflow

.github/workflows/release.yml, CHANGELOG.md
Goreleaser v2 should be used with goreleaser-action@v6
=> Feat: Upgrade goreleaser-action

.github/workflows/release.yml, .goreleaser.yml, CHANGELOG.md
Set version 2 in .goreleaser.yml
=> Use v2 in goreleaser configuration

.github/workflows/release.yml, .goreleaser.yml, CHANGELOG.md
=> Update deprecated fields in goreleaser configuraiton

ionoscloud/data_source_cube_server.go, ionoscloud/data_source_nic.go, ionoscloud/data_source_server.go, ionoscloud/resource_nic.go, ionoscloud/resource_server.go, ionoscloud/resource_server_cube.go, ionoscloud/resource_server_vcpu.go, ionoscloud/utils.go, services/cloudapi/cloudapinic/nic.go
=> Add security group serve nic

ionoscloud/data_source_datacenter.go, ionoscloud/resource_datacenter.go
=> Datacenter default nsg option

CHANGELOG.md, ionoscloud/resource_k8s_cluster.go, ionoscloud/resource_k8s_node_pool.go
=> fix: k8s cluster and nodepool should fail if state failed

docs/data-sources/apigateway_route.md, docs/resources/apigateway_route.md, ionoscloud/data_source_apigateway_route.go, ionoscloud/provider.go, ionoscloud/resource_apigateway_route.go, services/apigateway/route.go
=> feat: api gateway route resource

CHANGELOG.md, ionoscloud/resource_k8s_cluster_test.go, ionoscloud/test_constants.go, utils/constant/constants.go
=> fix: k8s and dataplatform tests

docs/data-sources/apigateway_route.md, docs/resources/apigateway.md, docs/resources/apigateway_route.md, ionoscloud/resource_apigateway.go, services/apigateway/apigateway.go
1. Rename apigateway_id to gateway_id
2. Add computed ID for gateway resource
3. remove a stray mariadb log line
4. use a common func for update/create funcs
=> refactor: a few useful refactors for gateway

docs/data-sources/apigateway.md
add docs for gateway datasource
=> doc: gateway datasrc

CHANGELOG.md, ionoscloud/data_source_dbaas_mongo_template.go
=> fix: make id for ionoscloud_mongo_template computed

docs/data-sources/apigateway_route.md, docs/resources/apigateway_route.md, ionoscloud/data_source_apigateway_route.go, ionoscloud/import_apigateway_route_test.go, ionoscloud/resource_apigateway_route.go, ionoscloud/resource_apigateway_route_test.go
=> test: api gateway route

README.md
=> update readme with s3 authentication

.github/workflows/test.yml, go.mod, go.sum, internal/framework/services/s3/object_resource_test.go, vendor/github.com/ionos-cloud/sdk-go-s3/api_buckets.go, vendor/github.com/ionos-cloud/sdk-go-s3/api_objects.go, vendor/github.com/ionos-cloud/sdk-go-s3/api_policy.go, vendor/github.com/ionos-cloud/sdk-go-s3/api_public_access_block.go, vendor/github.com/ionos-cloud/sdk-go-s3/api_tagging.go
- disabled known failing test for object resource with customer encryption
- update s3 sdk vendor
- expand testing to all folders in repo
=> run tests also for internal folder

gitbook_docs/summary.md
Adds NFS resources to gitbook summary
=> doc: add nfs to summary

docs/data-sources/s3_bucket.md, docs/data-sources/s3_bucket_policy.md, docs/data-sources/s3_object.md, docs/resources/s3_bucket.md, docs/resources/s3_bucket_policy.md, docs/resources/s3_object.md
=> doc: fix s3 resource name in examples

CHANGELOG.md, docs/resources/s3_bucket.md
=> doc: Add extra info in the documentation for s3 bucket resource

CHANGELOG.md, internal/framework/services/s3/bucket_policy_data_source.go, internal/framework/services/s3/bucket_policy_resource.go, internal/framework/services/s3/bucket_public_access_block_data_source.go, internal/framework/services/s3/bucket_public_access_block_resource.go, internal/framework/services/s3/bucket_resource.go
Fixes `produced a null value for` errors when specified bucket doesn't exist or has no policy or access block
=> Fix: policy, public access block error messages for data source

CHANGELOG.md, docs/resources/s3_bucket_policy.md, internal/framework/services/s3/bucket_policy_resource.go
=> fix: principal should be an array of strings in the docs

CHANGELOG.md, docs/resources/dbaas_inmemorydb_replica_set.md, ionoscloud/resource_dbaas_inmemorydb_replicaset.go, ionoscloud/resource_dbaas_inmemorydb_replicaset_test.go
=> Fix: InmemoryDB minor fixes

CHANGELOG.md, ionoscloud/resource_certificate_manager_auto_certificate_test.go, ionoscloud/resource_certificate_manager_provider_test.go
=> test: Add test tags for Ceritificate Manager files

CHANGELOG.md, docs/resources/apigateway_route.md, docs/resources/container_registry.md, docs/resources/dataplatform_cluster.md, docs/resources/dbaas_pgsql_cluster.md, docs/resources/group.md, docs/resources/ipfailover.md, docs/resources/k8s_cluster.md, docs/resources/kafka_cluster.md, docs/resources/kafka_topic.md, docs/resources/s3_key.md, docs/resources/user.md, docs/resources/vpn_ipsec_tunnel.md
=> fix: only valid hcl in resource examples

CHANGELOG.md, docs/resources/dbaas_mariadb_cluster.md, docs/resources/s3_bucket.md, internal/framework/services/s3/bucket_resource.go, internal/framework/services/s3/bucket_resource_test.go
Should fix crossplane generation.
=> fix: add id to s3 bucket

docs/resources/vpn_wireguard_gateway.md, go.mod, go.sum, services/cdn/distributions.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/client.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_distribution.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_distribution_create.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_distribution_metadata.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_distribution_properties.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_distribution_update.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_distributions.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_distributions_all_of.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_error.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_error_messages.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_ip_addresses.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_links.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_metadata.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_pagination.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_resource_state.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_routing_rule.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_upstream.go, vendor/github.com/ionos-cloud/sdk-go-bundle/products/cdn/v2/model_upstream_geo_restrictions.go, vendor/modules.txt
=> fix: go bundle with default value marshalling

docs/resources/nfs_cluster.md, docs/resources/nfs_share.md, ionoscloud/resource_nfs_cluster.go
=> fix: nfs nitpicks

CHANGELOG.md, ionoscloud/resource_cdn_distribution_test.go, ionoscloud/test_constants.go, services/cdn/distributions.go
=> fix: deref nil crash, check GeoRestrictions

CHANGELOG.md, docs/data-sources/logging_pipeline.md, docs/resources/logging_pipeline.md, docs/resources/volume.md, ionoscloud/data_source_logging_pipeline.go, ionoscloud/resource_cdn_distribution.go, ionoscloud/resource_kafka_cluster.go, ionoscloud/resource_logging_pipeline.go, ionoscloud/resource_logging_pipeline_test.go, ionoscloud/test_constants.go, services/logging/client.go, services/logging/pipeline.go
=> feat: add location to logging pipelines

CHANGELOG.md, ionoscloud/import_dbaas_mongo_cluster_test.go, services/dbaas/users.go
Add fixes for DBaaS tests that failed here: https://github.com/ionos-cloud/terraform-provider-ionoscloud/actions/runs/10389318799/job/28767057949
=> test: Fix DBaaS tests, set ID for Mongo user import

CHANGELOG.md, docs/data-sources/logging_pipeline.md, docs/resources/logging_pipeline.md, ionoscloud/data_source_logging_pipeline.go, ionoscloud/resource_logging_pipeline.go, services/logging/client.go
=> fix: location set as optional with de/txl default

xpprovider/provider.go
=> expose terraform sdk, framework providers for crossplane upjet use.

CHANGELOG.md, docs/resources/s3_bucket_public_access_block.md, gitbook_docs/summary.md, internal/framework/services/s3/resource_object_test.go, services/s3/lifecycle.go, services/s3/object.go, services/s3/object_lock.go, utils/hash/hash.go
fix md5 header bug and update tests
=> fix public access block documentation and md5 header functionality

docs/resources/s3_bucket_policy.md, ionoscloud/provider.go
=> expose sdk bundle client function for injecting the client in crossplane

services/kafka/client.go, services/kafka/topic.go
Fixes a typo in the `IsTopicDeleted` function
=> Fix: Kafka IsTopicDeleted

CHANGELOG.md
=> doc: Add Certificate Manager note in CHANGELOG.md

.github/workflows/k8s-test-run.yml
=> test: Modify k8s workflow - run tests weekly again

CHANGELOG.md, docs/resources/apigateway.md, docs/resources/ipblock.md, ionoscloud/resource_apigateway.go, ionoscloud/resource_apigateway_test.go, services/apigateway/apigateway.go
=> fix: certificate_id should be optional for api_gateway resource

CHANGELOG.md, ionoscloud/resource_cube_server.go
fix for https://github.com/ionos-cloud/terraform-provider-ionoscloud/issues/687
=> fix: set user_data and backup_unit_id in cube server

CHANGELOG.md, internal/framework/services/s3/resource_bucket_lifecycle_configuration.go, internal/framework/services/s3/resource_bucket_lifecycle_configuration_test.go
=> remove validation for empty prefix

CHANGELOG.md, README.md
=> doc: Add note about IP retrieval in 'README.md'

CHANGELOG.md, docs/data-sources/cube_server.md, docs/resources/cube_server.md, docs/resources/server.md, ionoscloud/data_source_cube_server.go, ionoscloud/import_s3_keys_test.go, ionoscloud/resource_cube_server.go, ionoscloud/resource_cube_server_test.go, ionoscloud/resource_server_test.go, ionoscloud/resource_volume.go, ionoscloud/test_constants.go
=> feat: cube server add hostname fix tests

CHANGELOG.md, docs/data-sources/cube_server.md, docs/data-sources/server.md, docs/data-sources/vcpu_server.md, docs/resources/cube_server.md, docs/resources/server.md, docs/resources/vcpu_server.md, docs/resources/volume.md, ionoscloud/data_source_cube_server.go, ionoscloud/data_source_server.go, ionoscloud/data_source_servers.go, ionoscloud/data_source_vcpu_server.go, ionoscloud/import_s3_keys_test.go, ionoscloud/resource_cube_server.go, ionoscloud/resource_cube_server_test.go, ionoscloud/resource_server.go, ionoscloud/resource_server_test.go, ionoscloud/resource_vcpu_server.go, ionoscloud/resource_vcpu_server_test.go, ionoscloud/resource_volume.go, ionoscloud/test_constants.go, utils/constant/constants.go
=> feature: add hostname to server and vcpu_server and servers

CHANGELOG.md, ionoscloud/resource_volume.go
=> fix empty ssh key crash

CHANGELOG.md, ionoscloud/import_vpn_ipsec_gateway_test.go, ionoscloud/import_vpn_wireguard_gateway_test.go, ionoscloud/resource_vpn_ipsec_gateway_test.go, ionoscloud/resource_vpn_wireguard_gateway_test.go, ionoscloud/test_constants.go
=> test: Add import tests for VPN Gateways

CHANGELOG.md, docs/resources/cube_server.md, docs/resources/server.md, docs/resources/vcpu_server.md, ionoscloud/resource_cube_server.go, ionoscloud/resource_server.go, ionoscloud/resource_server_test.go, ionoscloud/resource_vcpu_server.go
=> fix: hostname needs to be computed

CHANGELOG.md, gitbook_docs/summary.md
=> fix: docs for docs.ionos.com

README.md, gitbook_docs/README.md
=> doc: link examples

README.md
=> enhancement: remove basic auth deprecation notice from readme

CHANGELOG.md, ionoscloud/import_dbaas_mariadb_cluster_test.go, ionoscloud/resource_dbaas_mariadb_cluster_test.go
=> test: Add import tests for MariaDB clusters

.github/workflows/release.yml
=> fix: Fix release workflow

CHANGELOG.md, docs/resources/dbaas_pgsql_cluster.md, ionoscloud/data_source_certificate_manager_auto_certificate.go, ionoscloud/data_source_dbaas_inmemorydb_snapshot.go, ionoscloud/data_source_kafka_cluster.go, ionoscloud/data_source_kafka_topic.go, ionoscloud/data_source_nfs_cluster.go, ionoscloud/resource_certificate_manager_auto_certificate.go, ionoscloud/resource_certificate_manager_provider.go, ionoscloud/resource_datacenter.go, ionoscloud/resource_dbaas_inmemorydb_replicaset.go, ionoscloud/resource_dbaas_mariadb_cluster.go, ionoscloud/resource_dbaas_mongodb_cluster.go, ionoscloud/resource_dbaas_pgsql_cluster.go, ionoscloud/resource_kafka_cluster.go, ionoscloud/resource_logging_pipeline.go, ionoscloud/resource_nfs_cluster.go, ionoscloud/resource_vpn_ipsec_gateway.go, ionoscloud/resource_vpn_wireguard_gateway.go
=> fix: remove location validations

CHANGELOG.md, docs/resources/dbaas_inmemorydb_replica_set.md, docs/resources/kafka_cluster.md, docs/resources/kafka_topic.md, docs/resources/logging_pipeline.md, docs/resources/nfs_cluster.md, docs/resources/nfs_share.md, services/dbaas/inmemorydb/replica_set.go, services/kafka/client.go, services/logging/client.go, services/nfs/client.go
=> fix: Fix 'location' related bug for some resources

docs/resources/k8s_cluster.md, docs/resources/k8s_node_pool.md
=> doc: update k8s version

CHANGELOG.md, docs/data-sources/image.md, ionoscloud/data_source_image.go, ionoscloud/data_source_image_test.go
=> feat: Add 'expose_serial' attribute for image DS

CHANGELOG.md
=> doc: Remove 'upcoming-release' tag from CHANGELOG.md

CHANGELOG.md, ionoscloud/resource_k8s_cluster.go
=> fix: Set 'api_subnet_allow_list' even if the list is empty

CHANGELOG.md, docs/resources/server.md, ionoscloud/resource_server.go, ionoscloud/resource_server_test.go, ionoscloud/resource_vcpu_server_test.go
=> feat: make volume optional for ionoscloud_server

CHANGELOG.md, ionoscloud/resource_user.go
=> Fix: Group membership gone missing after reapply

.github/ISSUE_TEMPLATE/config.yml
=> docs: fix URL

CHANGELOG.md, docs/data-sources/object_storage_accesskey.md, docs/data-sources/object_storage_region.md, docs/resources/object_storage_accesskey.md, gitbook_docs/README.md, services/objectstoragemanagement/accesskeys.go, services/objectstoragemanagement/regions.go
=> feat: added env var to change url for object storage management

docs/data-sources/dbaas_mongo_user.md, docs/data-sources/ipfailover.md, docs/data-sources/share.md, docs/data-sources/vpn_ipsec_tunnel.md
=> docs: small fixes

.github/workflows/build.yml, .github/workflows/linter.yaml
=> chore: update actions

ionoscloud/resource_dbaas_inmemorydb_replicaset_test.go, ionoscloud/resource_dbaas_mariadb_cluster_test.go
=> fix: mariadb inmemorydb tests

docs/data-sources/s3_bucket.md, docs/data-sources/s3_bucket_policy.md, docs/data-sources/s3_object.md, docs/data-sources/s3_objects.md, docs/resources/s3_bucket.md, docs/resources/s3_bucket_cors_configuration.md, docs/resources/s3_bucket_lifecycle_configuration.md, docs/resources/s3_bucket_object_lock_configuration.md, docs/resources/s3_bucket_policy.md, docs/resources/s3_bucket_public_access_block.md, docs/resources/s3_bucket_server_side_encryption_configuration.md, docs/resources/s3_bucket_versioning.md, docs/resources/s3_bucket_website_configuration.md, docs/resources/s3_object.md, docs/resources/s3_object_copy.md
=> Add note related to user-owned buckets not being supported

CHANGELOG.md, services/dbaas/inmemorydb/replica_set.go
=> fix: fail on FAILED state for inmemorydb replicaset

CHANGELOG.md, ionoscloud/data_source_s3_key.go, ionoscloud/resource_s3_key_test.go
=> feat: only user_id should be required for ionosclud_s3_key data source

CHANGELOG.md, docs/data-sources/dbaas_mariadb_cluster.md, docs/resources/dbaas_mariadb_cluster.md, ionoscloud/data_source_dbaas_mariadb_cluster.go, ionoscloud/resource_dbaas_mariadb_cluster.go, ionoscloud/resource_dbaas_mariadb_cluster_test.go, ionoscloud/test_constants.go, services/dbaas/mariadb/cluster.go
=> feat:/backup location for mariadb

CHANGELOG.md, ionoscloud/import_dataplatform_node_pool_test.go, ionoscloud/resource_dataplatform_nodepool.go, utils/constant/constants.go
Solves the bug presented in: https://github.com/ionos-cloud/terraform-provider-ionoscloud/issues/797
=> fix: Fix import bug for Dataplatform node pool

ionoscloud/resource_dbaas_inmemorydb_replicaset_test.go, ionoscloud/resource_nfs_cluster_test.go, ionoscloud/test_constants.go
=> fix: move temporaryConfigSetup to test_constants file to avoid redefinitions

CHANGELOG.md, docs/data-sources/server.md, docs/resources/server.md
=> doc: better docs for dedicated core

ionoscloud/resource_nfs_cluster_test.go
=> fix: nfs cluster test

CHANGELOG.md, services/apigateway/apigateway.go, services/cdn/distributions.go, services/containerregistry/registries.go, services/dataplatform/cluster.go, services/dbaas/cluster.go, services/dbaas/database.go, services/dbaas/inmemorydb/replica_set.go, services/dbaas/mariadb/cluster.go, services/dbaas/users.go, services/nfs/cluster.go
=> fix: error on failed state

CHANGELOG.md, docs/resources/user.md
=> doc: add example using password_wo for user resource

internal/framework/provider/provider.go
=> chore: remove warnings when there is no object storage auth

CHANGELOG.md, ionoscloud/resource_s3_key_test.go
=> fix: s3 key test

CHANGELOG.md, ionoscloud/resource_dbaas_inmemorydb_replicaset_test.go, ionoscloud/resource_dbaas_mariadb_cluster_test.go, ionoscloud/resource_lan.go, ionoscloud/test_constants.go
=> fix: ionoscloud_lan should retry if lan is delete-protected

ionoscloud/resource_apigateway_route.go, ionoscloud/resource_kafka_cluster.go, ionoscloud/resource_kafka_topic.go, ionoscloud/resource_logging_pipeline.go, ionoscloud/resource_vpn_ipsec_gateway.go, ionoscloud/resource_vpn_ipsec_tunnel.go
=> fix: fmt error

.github/workflows/e2e.yaml, .github/workflows/pr-comment-trigger.yaml
=> Test comment on pr

.github/workflows/e2e.yaml, .github/workflows/pr-comment-trigger.yaml
=> feat: pr comment path

.github/workflows/pr-comment-trigger.yaml
=> feat: workflow ref

.github/workflows/e2e.yaml
=> feat: pr number

.github/workflows/e2e.yaml
=> feat: checkout before gh

CHANGELOG.md, docs/resources/kafka_cluster.md, docs/resources/kafka_topic.md
=> feat: kafka 3.9.0

CHANGELOG.md, docs/resources/datacenter.md
=> TWT-2381 Fix Formats in Terraform VDC

README.md
=> docs: add config file info to README.md

CHANGELOG.md, docs/data-sources/nfs_cluster.md, docs/data-sources/nfs_share.md, docs/resources/nfs_cluster.md, docs/resources/nfs_share.md, services/nfs/client.go
=> refactor: Add new 'de/fra/2' location for NFS
